name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the app
        env:
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
        run: npm run deploy